apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  #accessModes:
    #- ReadWriteOnce
  #storageClassName: sqlserver
  hostPath:
    path: /sqldata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
<<<<<<< HEAD
  namespace: practicainnovar  
  #namespace : default
=======
  #namespace: practicainnovar  
  namespace: default  
>>>>>>> e5ac38c3d02a6a01853da0e4d2f7c945f9d77090
spec:
  #storageClassName: sqlserver
  accessModes:
    - ReadWriteMany
  #accessModes:
    #ReadWriteOnce
  resources:
    requests:
      storage: 3Gi