apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: practicainnovar
  #namespace : default
  labels:
    app: db
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433